name: SimpleNameTag
main: eu.cloudnetservice.simplenametag.SimpleNameTagPlugin
version: ${nametag.version}

api-version: 1.13
author: TheMeinerLP

depend: [CloudNetAPI]

description: CloudNet SimpleNameTagSystem
website: https://cloudnetservice.eu/

